/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: polyman (https://sketchfab.com/Polyman_3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/apple-iphone-15-pro-max-black-df17520841214c1792fb8a44c6783ee7
Title: Apple iPhone 15 Pro Max Black
*/

import * as THREE from 'three';
import React, { useEffect } from 'react';
import { useGLTF, useTexture } from '@react-three/drei';

function Model({ item, ...props }) {
  const { nodes, materials } = useGLTF('/models/scene.glb');
  const texture = useTexture(item.img);

  useEffect(() => {
    Object.entries(materials).forEach(([key, material]) => {
      // Exclude specific materials from color updates
      if (
        ![
          'zFdeDaGNRwzccye',
          'ujsvqBWRMnqdwPx',
          'hUlRcbieVuIiOXG',
          'jlzuBkUzuJqgiAK',
          'xNrofRCqOXXHVZt',
        ].includes(key)
      ) {
        material.color = new THREE.Color(item.color[0]);
        material.needsUpdate = true;
      }
    });
  }, [materials, item]);

  return (
    <group {...props} dispose={null}>
      {Object.entries(nodes).map(([key, node]) => (
        <mesh
          key={key}
          castShadow
          receiveShadow
          geometry={node.geometry}
          material={materials[node.material?.name] || node.material}
          scale={0.01}
        >
          {key === 'xXDHkMplTIDAXLN' && (
            <meshStandardMaterial roughness={1} map={texture} />
          )}
        </mesh>
      ))}
    </group>
  );
}

export default Model;

useGLTF.preload('/models/scene.glb');
